import { StyleSheet } from "react-native";

export const stylesCatalog = StyleSheet.create({
  AcButton: {
    backgroundColor: "#27546C",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    alignSelf: "center",
    width: 300,
  },
  AcContainer: {
      padding: 10,
  },
  Acmt20: {
      marginTop: "5%",
  },
  AcverticallySpaced: {
      paddingTop: 4,
      paddingBottom: 4,
      alignSelf: "stretch",
  },
  articleText: {
      marginTop: 5,
      alignSelf: "flex-start",
      padding: 10,
      fontWeight: "bold",
      fontSize: 22,
      color: "black",
  },
  boxCard: {
      borderWidth: 2,
      borderColor: "white",
      width: 171,
      height: 160,
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      borderRadius: 25,
      backgroundColor: "#27546C",
      borderWidth: 1,
      borderColor: "gray",
      left: "51%",
      top: 10,
  },
  boxHome: {
      borderWidth: 2,
      borderColor: "#27546C",
      alignItems: "center",
      textAlign: "center",
      borderBottomLeftRadius: 25,
      borderBottomRightRadius: 25,
      backgroundColor: "#27546C",
      height: 220,
  },
  boxLogin: {
      borderWidth: 2,
      borderColor: "#27546C",
      alignItems: "center",
      textAlign: "center",
      borderBottomLeftRadius: 25,
      borderBottomRightRadius: 25,
      backgroundColor: "#27546C",
      height: 150,
  },
  boxNews: {
      borderWidth: 2,
      borderColor: "#27546C",
      alignItems: "center",
      textAlign: "center",
      borderBottomLeftRadius: 25,
      borderBottomRightRadius: 25,
      backgroundColor: "#27546C",
      height: 150,
  },
  boxStatistics: {
      borderWidth: 2,
      borderColor: "#27546C",
      alignItems: "center",
      textAlign: "center",
      borderBottomLeftRadius: 25,
      borderBottomRightRadius: 25,
      backgroundColor: "#27546C",
      height: 150,
  },
  boxNews: {
      borderWidth: 2,
      borderColor: "#27546C",
      alignItems: "center",
      textAlign: "center",
      borderBottomLeftRadius: 25,
      borderBottomRightRadius: 25,
      backgroundColor: "#27546C",
      height: 120,
  },
  cardImage: {
      height: 130,
      width: "100%",
  },
  cards: {
      marginTop: -95,
  },
  cardStyle: {
      margin: 10,
      borderWidth: 1,
      borderColor: "gray",
  },
  cardsTitle: {
      alignSelf: "center",
      position: "absolute",
      marginTop: 5,
      color: "white",
      fontWeight: "bold",
      flexShrink: 12,
      fontSize: 16,
  },
  container: {
      flex: 1,
      backgroundColor: "white",
  },
  container2: {
      height: 70,
      width: 164,
      borderRadius: 30,
      padding: 15,
      marginLeft: 20,
      marginBottom: 20,
  },
  covidHeading: {
      color: "#FFF",
      fontSize: 28,
      alignSelf: "center",
      fontWeight: "bold",
      margin: 25,
      marginTop: "10%",
  },
  casesHeading: {
      marginTop: 20,
      color: "black",
      fontSize: 15,
      alignSelf: "center",
      fontWeight: "bold",
      textAlign: "center",
  },
  countryName: {
      fontSize: 15,
      color: "black",
      fontWeight: "bold",
  },
  col: {
      flexDirection: "row",
      marginBottom: 20,
  },
  flag: {
      height: 30,
      width: 40,
      padding: 10,
      borderRadius: 1000,
  },
  flatList: {
      flex: 1,
      alignItems: "stretch",
      marginTop: 10,
      borderTopWidth: 2,
      borderColor: "black",
  },
  Global: {
      borderRadius: 50,
      backgroundColor: "#FFFFFF",
      position: "absolute",
      width: 126,
      height: 31,
      top: 120,
      left: 200,
  },
  globalText: {
      //fontFamily: 'Roboto',
      color: "black",
      position: "absolute",
      fontSize: 20,
      alignSelf: "center",
      fontWeight: "bold",
      margin: 3,
  },
  homeButton: {
      borderRadius: 30,
      backgroundColor: "#3F414E",
      position: "absolute",
      top: "80%",
      justifyContent: "center",
      position: "absolute",
      width: 120,
      height: 35,
      borderRightWidth: 2,
      borderLeftWidth: 2,
      borderColor: "white",
  },
  homeButtonHeading: {
      color: "white",
      position: "absolute",
      fontSize: 16,
      alignSelf: "center",
      fontWeight: "bold",
      margin: 10,
  },
  HomeContainer: {
      flex: 1,
      flexDirection: "row",
  },
  Homeimage: {
      width: "110%",
      height: 165,
      resizeMode: "center",
      borderRadius: 50,
  },
  Homeimage2: {
      width: "100%",
      height: 165,
      width: 170,
      resizeMode: "cover",
      borderRadius: 50,
  },
  Homecard: {
      width: 150,
      marginLeft: 10,
      marginRight: 20,
  },
  Hometext: {
      marginTop: 15,
      marginLeft: 10,
      textAlign: "center",
      fontSize: 16,
      color: "black",
  },
  inputStyle: {
      alignSelf: "center",
      padding: 13,
      borderWidth: 4,
      borderColor: "#27546C",
      borderRadius: 30,
      width: "100%",
  },
  labelStyle: {
      color: "#27546C",
      fontSize: 16,
      fontWeight: "700",
      padding: 10,
  },
  Logincontainer: {
      marginTop: 5,
      padding: 12,
  },
  LoginboxLogin: {
      borderWidth: 2,
      borderColor: "#27546C",
      alignItems: "center",
      textAlign: "center",
      borderBottomLeftRadius: 25,
      borderBottomRightRadius: 25,
      backgroundColor: "#27546C",
      height: 300,
  },
  LogininputStyle:{
      padding: 13,
      borderWidth: 4,
      borderColor: "#27546C",
      borderRadius: 30,
      width: 350,
  },
  LoginlabelStyle:{
      color:'#27546C',
      fontSize:16,
      fontWeight:'700',
      padding:12,
  },
  LogincovidHeading: {
      color: "#F19B1F",
      fontSize: 32,
      alignSelf: "center",
      fontWeight: "bold",
      margin: 25,
      marginTop: "15%",
  },
  LoginverticallySpaced: {
      paddingTop: 2,
      paddingBottom: 4,
      alignSelf: "center",
  },
  Loginbutton:{
      backgroundColor: '#27546C',
      padding: 10,
      borderRadius: 5,
      alignItems: 'center',
      alignSelf:'center',
      width:250
  },
  Loginmt20: {
      marginTop: 10,
  },
  mapButton: {
      borderRadius: 50,
      backgroundColor: "#35464F",
      position: "absolute",
      top: "5%",
      right: "5%",
      width: 80,
      height: 45,
  },
  map: {
      flex: 1,
      width: "100%",
      height: "100%",
  },
  number: {
      fontWeight: "500",
      color: "white",
      justifyContent: "center",
      alignSelf: "center",
      marginTop: 0,
  },
  newsScrollContainer:{
      marginBottom:150
  },
  newsContainer: {
      flex: 1,
      backgroundColor: "white",
  },
    
  newsContainer: {
      flex: 1,
      backgroundColor: "white",
      paddingVertical: 10,
  },
  newsItem: {
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: "#ccc",
  },
  newsImage: {
      width: "100%",
      height: 200,
      marginBottom: 10,
  },
  newsTitle: {
      padding:5,
      fontSize: 16,
      fontWeight: "bold",
      color: "#000",
  },
  notification: {
      color: "#FFF",
      fontSize: 16,
      alignSelf: "flex-end",
      fontWeight: "bold",
      margin: 20,
      marginTop: "15%",
  },
  preventionText: {
      marginTop: 5,
      alignSelf: "flex-start",
      padding: 10,
      fontWeight: "bold",
      fontSize: 22,
      color: "black",
  },
  prevCardStyle: {
      height: 100,
      marginTop: 25,
      borderRadius: 100,
  },
  rows: {
      width: "100%",
      marginTop: 10,
      marginBottom: 8,
      padding: 10,
  },
  scrollContainer: {
      marginBottom: 150,
  },
  Turkey: {
      borderRadius: 50,
      backgroundColor: "#263238",
      position: "absolute",
      width: 241,
      height: 31,
      top: 120,
      left: 85,
  },
  turkeyText: {
      //fontFamily: 'Roboto',
      position: "absolute",
      color: "white",
      fontSize: 20,
      alignSelf: "flex-start",
      fontWeight: "bold",
      paddingLeft: 25,
      margin: 3,
  },
  totalCases: {
      fontSize: 16,
      color: "black",
      fontWeight: "bold",
      marginTop: 5,
  },
  titleBigBox: {
      alignSelf: "center",
      position: "absolute",
      marginTop: 5,
      color: "#533219",
      fontWeight: "bold",
      //flexShrink: 12,
      fontSize: 16,
  },
  tabBarStyle: {
      position: "absolute",
      borderRadius: 15,
  },
  
});

export default stylesCatalog;
